Vagrant.configure("2") do |config|
    # Define VM 1: server01
    config.vm.define "server01" do |server01|
      server01.vm.box = "17012626-a970-11ef-9612-ee0d48c3b67e"
      ## server01.vm.box_version = "4.3.12"
      server01.vm.hostname = "server01"
      server01.vm.network "public_network", bridge: nil  # Bridged network
  
      server01.vm.provider "virtualbox" do |vm|
        vm.name = "server01"
        vm.memory = 1024
        vm.cpus = 2
      end
    end
  end
  