Vagrant.configure("2") do |config|
    # Define VM 1: server01
    config.vm.define "server01" do |server01|
      server01.vm.box = "generic/alpine317"
      ## server01.vm.box_version = "4.3.12"
      server01.vm.hostname = "server01"
      server01.vm.network "public_network", bridge: nil  # Bridged network
      ## server01.vm.provision "shell", path: "rabbitmq.sh"
      
      server01.vm.provider "virtualbox" do |vm|
        vm.name = "server01"
        vm.memory = 8024
        vm.cpus = 6
      end
    end
  end
  